### ISSUE TITLE
What are the prerequisite to use libRootJava?

### ISSUE THREAD

**Issue by ymohammad** [Chainfire/librootjava#6]
Hi,

I would like to know the Prerequistes to use this library. With this library, will I able to execute my Mobile App with Root access? Do we still need to Root the phone before using this library?

Thanks.

**Comment by zhanghai** [comment]
Yes, user needs to root their phone and grant root access to your app before your app can run as root.

**Comment by ymohammad** [comment]
Thanks @zhanghai
